# Generated by Django 5.1 on 2024-09-22 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('airline_name', models.CharField(max_length=100)),
                ('airline_image', models.ImageField(upload_to='images/')),
                ('airline_type', models.TextField()),
            ],
            options={
                'db_table': 'Airline',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('airport', models.CharField(default='coming soon...', max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.DurationField(null=True)),
                ('depart_time', models.TimeField(default=1)),
                ('arrival_time', models.TimeField(default=1)),
                ('destination', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='admin_part.place')),
                ('origin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='admin_part.place')),
            ],
        ),
    ]
