# Generated by Django 5.1 on 2024-09-22 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='admin_part.airline'),
        ),
    ]
