# Generated by Django 5.1 on 2024-09-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0002_flight_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='airline_type',
            field=models.CharField(max_length=100),
        ),
    ]
