# Generated by Django 4.2.16 on 2024-10-19 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0006_alter_airline_airline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='airline',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='delete_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airline',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2),
        ),
    ]
