# Generated by Django 4.2.16 on 2024-10-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0009_remove_flight_arrival_time_remove_flight_depart_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='economy_price',
        ),
    ]
