# Generated by Django 4.2.16 on 2024-10-19 14:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0012_remove_airline_airline_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('apid', models.AutoField(primary_key=True, serialize=False)),
                ('airport_name', models.CharField(default='coming soon...', max_length=100)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2)),
                ('delete_flag', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='admin_part.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='admin_part.airport'),
        ),
        migrations.DeleteModel(
            name='place',
        ),
    ]
