# Generated by Django 4.2.16 on 2024-10-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0013_airport_alter_flight_destination_alter_flight_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='origin',
        ),
        migrations.AddField(
            model_name='flight',
            name='from_airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_airport', to='admin_part.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='to_airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_airport', to='admin_part.airport'),
        ),
    ]
