# Generated by Django 4.2.16 on 2024-10-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0014_remove_flight_destination_remove_flight_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
