# Generated by Django 4.2.16 on 2024-11-04 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0016_alter_flight_estimated_arrival'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
