# Generated by Django 4.2.16 on 2024-11-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0019_rename_class_type_booking_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='business_class_slots',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='economy_slots',
        ),
    ]
