# Generated by Django 5.1.3 on 2024-11-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0020_remove_flight_business_class_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
