# Generated by Django 3.1.2 on 2024-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
