# Generated by Django 4.2.16 on 2024-10-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0003_alter_usertable_first_name_alter_usertable_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='user_mail',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='user_password',
        ),
    ]
