# Generated by Django 4.2.16 on 2024-10-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0004_remove_usertable_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='usertable',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='usertable',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50),
        ),
        migrations.AddField(
            model_name='usertable',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='usertable',
            name='passport_number',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='usertable',
            name='phone_number',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
