# Generated by Django 4.2.16 on 2024-10-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0005_usertable_address_usertable_email_usertable_gender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usertable',
            new_name='Passenger',
        ),
        migrations.AlterModelTable(
            name='passenger',
            table='Passenger',
        ),
    ]
