# Generated by Django 4.2.16 on 2024-10-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0006_rename_usertable_passenger_alter_passenger_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='type',
            field=models.CharField(choices=[('1', 'Business Class'), ('2', 'Economy')], default='2', max_length=50),
        ),
    ]
