# Generated by Django 4.2.16 on 2024-10-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0007_passenger_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default=None, max_length=100)),
                ('phone_number', models.CharField(default=None, max_length=20)),
                ('message', models.TextField(default=None, max_length=1000)),
            ],
            options={
                'db_table': 'ContactUs',
            },
        ),
    ]
