# Generated by Django 4.2.16 on 2024-11-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0008_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('passengers', models.ManyToManyField(to='user_part.passenger')),
            ],
        ),
    ]
