# Generated by Django 4.2.16 on 2024-11-04 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0009_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
